FROM jenkins/jenkins:lts

USER root

# Install docker cli + basic tools
RUN apt-get update && apt-get install -y docker.io curl unzip && rm -rf /var/lib/apt/lists/*

# Install Sonar Scanner
RUN curl -sSLo /tmp/sonar.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip \
    && unzip /tmp/sonar.zip -d /opt \
    && ln -s /opt/sonar-scanner-*/bin/sonar-scanner /usr/local/bin/sonar-scanner \
    && rm /tmp/sonar.zip

USER jenkins
